### ISSUE TITLE
Model is a type "<class: type>"

### ISSUE THREAD

**Issue by raceee** [isears/NIS-CR-ComplicationPredictor#19]
The ```GradientExplainer``` is having a problem because the model that we are trying to pass through is not of type ```nn.Module```. This is most likely due to the model's ```.pkl``` serialization.

@isears Since we are using skorch the model is embedded into the NeuralNetClassifier class within skorch. I think we need to call this https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=load_state_dict#torch.nn.Module.load_state_dict

https://github.com/isears/NIS-CR-ComplicationPredictor/blob/288fa0afee4333d0fbd3afccaae7d3f99613d495/shap_figure.py#L23-L37

**Comment by raceee** [comment]
Do you agree?

**Comment by isears** [comment]
Yes, I agree.

We should be able to access the underlying pytorch module from the skorch object just by doing something like:
`trained_classifier.module`

Once we have that and we've verified that it's a reference to a pytorch module, we can load and save it using the standard pytorch API: https://pytorch.org/tutorials/beginner/saving_loading_models.html

Skorch is really only useful as an abstraction for the training phase. We don't necessarily need it for the shap phase.

**Comment by raceee** [comment]
Ok you will see a commit incoming soon. You mentioned using more cores or a GPU option, but I don't see that in the GradientExplainer docs.

**Comment by isears** [comment]
Hopefully it just does it automatically but don't worry if not. Only a theory

**Comment by raceee** [comment]
> I really think what it means is that:
> 
> https://github.com/isears/NIS-CR-ComplicationPredictor/blob/288fa0afee4333d0fbd3afccaae7d3f99613d495/modelingMain.py#L37-L51
> 
> Needs to just save the state of the NN and not the entire skorch routine

Weird... it seems that once you pass the model into the NeuralNetClassifer it changes the type of the PyTorch model to a ```<class: type>```.  This is where to search.

**Comment by isears** [comment]
Or actually, maybe it would be simpler to load the model as it's pickled now and just try to dig out the pytorch model right before you start using the gradientexplainer

**Comment by isears** [comment]
Ah, I think I remember this, it's not `.module` it's `.module_`

Try that

<img width="573" alt="image" src="https://github.com/isears/NIS-CR-ComplicationPredictor/assets/7016326/d5fd60ee-c1a8-49ad-8156-e4f52c570bfb">
